blog/urls.py
from django.urls import path

from blog.apps import BlogConfig
from blog.views import (ArticleCreateView, ArticleDeleteView,
                        ArticleDetailView, ArticleListView, ArticleUpdateView)

app_name = BlogConfig.name


urlpatterns = [
    path("", ArticleListView.as_view(), name="article_list"),
    path("article_detail/<int:pk>", ArticleDetailView.as_view(), name="article_detail"),
    path("create/", ArticleCreateView.as_view(), name="article_create"),
    path("update/<int:pk>", ArticleUpdateView.as_view(), name="article_update"),
    path("delete/<int:pk>", ArticleDeleteView.as_view(), name="article_delete"),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("catalog.urls", namespace="catalog")),
    path("blogs/", include("blog.urls", namespace="blog")),
    path("users/", include("users.urls", namespace="users")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models


class Article(models.Model):
    title = models.CharField(
        max_length=50, verbose_name="Заголовок", help_text="Введите название заголовка"
    )

    content = models.TextField(
        verbose_name="Контент",
        help_text="Введите контент",
    )

    created_at = models.DateField(auto_now_add=True)

    photo = models.ImageField(verbose_name="Изображение", upload_to="blog/photo/")

    is_published = models.BooleanField(
        verbose_name="Подтверждение публикации",
        help_text="Подтвердите публикацию",
        default=False,
    )

    views_counter = models.PositiveIntegerField(
        verbose_name="Колличество просмотров",
        help_text="Введите колличество просмотров",
        default=0,
    )

    class Meta:
        verbose_name = "Статья"
        verbose_name_plural = "Статьи"

    def __str__(self):
        return self.title

blog/views.py
from django.urls import reverse, reverse_lazy
from django.views.generic import (CreateView, DeleteView, DetailView, ListView,
                                  UpdateView)

from blog.models import Article


class ArticleListView(ListView):
    model = Article

    def get_queryset(self):
        queryset = super().get_queryset()
        return queryset.filter(is_published=True)


class ArticleDetailView(DetailView):
    model = Article

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        self.object.views_counter += 1
        self.object.save()
        return self.object


class ArticleCreateView(CreateView):
    model = Article
    fields = ("title", "content", "photo", "is_published")
    success_url = reverse_lazy("blog:article_list")


class ArticleUpdateView(UpdateView):
    model = Article
    fields = ("title", "content", "photo")
    success_url = reverse_lazy("blog:article_list")

    def get_success_url(self):
        return reverse("blog:article_detail", args=[self.kwargs.get("pk")])


class ArticleDeleteView(DeleteView):
    model = Article
    success_url = reverse_lazy("blog:article_list")

blog/templates/blog/article_confirm_delete.html
{% extends 'base_block.html' %}
{% block content %}
<div class="d-flex justify-content-center align-items-center">
    <form method="post" class="" enctype="multipart/form-data">
        <div class="card">
            <p class="card-text mx-4 mt-3">Действительно хотите удалить статью "{{ article.title }}"?</p>
            <div class="card-body">
                {% csrf_token %}
                {{ form.as_p }}
            </div>
            <button type="submit" class="btn btn-primary mb-3 mx-4">Удалить</button>
            <a class="btn btn-primary mx-4 mb-3" href="{% url 'blog:article_detail' article.pk %}" role="button">Отменить</a>
        </div>
    </form>
</div>
{% endblock %}

blog/templates/blog/article_detail.html
{% extends 'base_block.html' %}
{% load my_tags %}
{% block content %}
<div class="card mb-3">
    <img src="{{ article.photo|media_filter }}" class="card-img-top" alt="...">
    <div class="card-body">
        <h5 class="card-title">{{ article.title }}</h5>
        <p class="card-text">{{ article.content }}</p>
        <a href="{% url 'blog:article_update' article.pk %}" class="btn btn-primary">Изменить</a>
        <a href="{% url 'blog:article_list' %}" class="btn btn-primary">Назад</a>
        <a href="{% url 'blog:article_delete' article.pk %}" class="btn btn-outline-danger">Удалить</a>
        <p class="card-text mt-2"><small class="text-body-secondary">{{ article.created_at|date:'d M Y' }}</small></p>
    </div>
</div>
{% endblock %}

blog/templates/blog/article_form.html
{% extends 'base_block.html' %}
{% block content %}
<div class="d-flex justify-content-center align-items-center">
    <form method="post" class="" enctype="multipart/form-data">
        <div class="card">
            <div class="card-body">
                {% csrf_token %}
                {{ form.as_p }}
            </div>
            <button type="submit" class="btn btn-primary mb-3 mx-4">
                {% if object %}
                Сохранить
                {% else %}
                Создать
                {% endif %}
            </button>
            <a href="{% url 'blog:article_list' %}" class="btn btn-primary mb-3 mx-4">Назад</a>
        </div>
    </form>
</div>
{% endblock %}

blog/templates/blog/article_list.html
{% extends 'base_block.html' %}
{% load my_tags %}
{% block content %}
<div class="row mb-2">
    {% for article in object_list %}
    <div class="col-md-6">
        <div class="card mb-3">
            <img src="{{ article.photo|media_filter }}" class="card-img-top" height="300">
            <div class="card-body">
                <h5 class="card-title">{{ article.title }}</h5>
                <p class="card-text mb-auto">{{ article.content|truncatechars:90 }}</p>
                <a href="{% url 'blog:article_detail' article.pk %}" class="card-link">Продолжить читать</a>
                <p class="card-text"><small class="text-body-secondary">{{ article.created_at|date:'d M Y' }}</small></p>
            </div>
        </div>
    </div>
    {% endfor %}
    <hr class="featurette-divider">
</div>
{% endblock %}