blog/urls.py
from django.urls import path

from blog.apps import BlogConfig
from blog.views import (ArticleCreateView, ArticleDeleteView,
                        ArticleDetailView, ArticleListView, ArticleUpdateView)

app_name = BlogConfig.name


urlpatterns = [
    path("", ArticleListView.as_view(), name="article_list"),
    path("article_detail/<int:pk>", ArticleDetailView.as_view(), name="article_detail"),
    path("create/", ArticleCreateView.as_view(), name="article_create"),
    path("update/<int:pk>", ArticleUpdateView.as_view(), name="article_update"),
    path("delete/<int:pk>", ArticleDeleteView.as_view(), name="article_delete"),
]

catalog/urls.py
from django.urls import path

from catalog.apps import CatalogConfig
from catalog.views import (ContactView, ProductCreateView, ProductDeleteView,
                           ProductDetailView, ProductListView,
                           ProductUpdateView, CategoryListView, ProductByCategory)

app_name = CatalogConfig.name

urlpatterns = [
    path("", ProductListView.as_view(), name="home_view"),
    path("contacts/", ContactView.as_view(), name="contacts_view"),
    path("product_detail/<int:pk>", ProductDetailView.as_view(), name="product_detail"),
    path("product_create/", ProductCreateView.as_view(), name="product_create"),
    path(
        "product_update/<int:pk>/", ProductUpdateView.as_view(), name="product_update"
    ),
    path(
        "product_delete/<int:pk>/", ProductDeleteView.as_view(), name="product_delete"
    ),
    path('categories/', CategoryListView.as_view(), name='category-list'),
    path('product-by-category/<int:pk>/', ProductByCategory.as_view(), name='product-by-category')
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("catalog.urls", namespace="catalog")),
    path("blogs/", include("blog.urls", namespace="blog")),
    path("users/", include("users.urls", namespace="users")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

catalog/models.py
from django.db import models

from users.models import User


class Product(models.Model):
    name = models.CharField(
        max_length=50,
        verbose_name="Название продукта",
        help_text="Введите название продукта",
    )
    description = models.TextField(
        verbose_name="Описание продукта",
        help_text="Введите описание продукта",
        blank=True,
        null=True,
    )
    photo = models.ImageField(upload_to="catalog/photo/", verbose_name="Фотография")
    category = models.ForeignKey(
        "Category", on_delete=models.CASCADE, related_name="products"
    )
    price = models.IntegerField(verbose_name="Цена")
    created_at = models.DateField(auto_now_add=True)
    updated_at = models.DateField(auto_now=True)
    publication_status = models.BooleanField(
        default=False, verbose_name="Флаг для публикации"
    )
    owner = models.ForeignKey(
        to=User,
        on_delete=models.CASCADE,
        verbose_name="Владелец",
        help_text="Укажите владельца",
    )

    class Meta:
        verbose_name = "Продукт"
        verbose_name_plural = "Продукты"
        permissions = [("can_unpublish_product", "Can unpublish product")]

    def __str__(self):
        return self.name


class Category(models.Model):
    name = models.CharField(
        max_length=50,
        verbose_name="Наименование категории",
        help_text="Введите наименование категории",
    )
    description = models.TextField(
        verbose_name="Описание категории",
        help_text="Введите описание категории",
        blank=True,
        null=True,
    )

    class Meta:
        verbose_name = "Категория"
        verbose_name_plural = "Категории"

    def __str__(self):
        return self.name

catalog/forms.py
from django.core.exceptions import ValidationError
from django.forms import BooleanField, ModelForm

from catalog.models import Product

FORBIDDEN_WORDS = [
    "казино",
    "криптовалюта",
    "крипта",
    "биржа",
    "дешево",
    "бесплатно",
    "обман",
    "полиция",
    "радар",
]


class StyleFormMixin:
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for fild in self.fields.values():
            if isinstance(fild, BooleanField):
                fild.widget.attrs.update({"class": "form-check-input"})
            else:
                fild.widget.attrs.update({"class": "form-control"})


class ProductForm(StyleFormMixin, ModelForm):
    class Meta:
        model = Product
        exclude = ("owner",)

    def clean_price(self):
        price = super().clean()["price"]
        if price < 0:
            raise ValidationError("Цена не может быть меньше 0")
        return price

    def clean_description(self):
        description = self.cleaned_data.get("description")
        for word in FORBIDDEN_WORDS:
            if word in description.lower():
                raise ValidationError("Нельзя вводить запрещенные слова")
        return description

    def clean_name(self):
        name = self.cleaned_data.get("name")
        for word in FORBIDDEN_WORDS:
            if word in name.lower():
                raise ValidationError("Нельзя вводить запрещенные слова")
        return name


class ProductFormLimited(ProductForm):
    class Meta:
        model = Product
        exclude = ("publication_status", "owner")

catalog/views.py
from django.contrib.auth.mixins import (LoginRequiredMixin, )
from django.core.exceptions import PermissionDenied
from django.urls import reverse_lazy
from django.views.generic import (CreateView, DeleteView, DetailView, ListView,
                                  TemplateView, UpdateView)
from django.utils.decorators import method_decorator
from django.views.decorators.cache import cache_page
from django.core.cache import cache

from catalog.forms import ProductForm, ProductFormLimited
from catalog.models import Product, Category

from catalog.services import products_by_category


class ContactView(TemplateView):
    template_name = "catalog/contacts.html"


class ProductListView(ListView):
    model = Product

    def get_queryset(self):
        queryset = cache.get('product_list')
        if not queryset:
            queryset = super().get_queryset()
            cache.set('product_list', queryset, 60 * 15)
        return queryset


@method_decorator(cache_page(60 * 15), name='dispatch')
class ProductDetailView(DetailView):
    model = Product


class ProductCreateView(LoginRequiredMixin, CreateView):
    model = Product
    form_class = ProductForm
    success_url = reverse_lazy("catalog:home_view")

    def form_valid(self, form):
        form.instance.owner = self.request.user
        return super().form_valid(form)


class ProductUpdateView(LoginRequiredMixin, UpdateView):
    model = Product
    success_url = reverse_lazy("catalog:home_view")

    def get_form_class(self):
        user = self.request.user
        if user.has_perm("can_unpublish_product"):
            return ProductForm
        else:
            return ProductFormLimited

    def get_object(self, queryset=None):
        obj = super().get_object(queryset=queryset)
        if obj.owner == self.request.user or self.request.user.has_perm(
                "can_unpublish_product"
        ):
            return obj
        else:
            raise PermissionDenied


class ProductDeleteView(LoginRequiredMixin, DeleteView):
    model = Product
    success_url = reverse_lazy("catalog:home_view")

    def get_object(self, queryset=None):
        obj = super().get_object(queryset=queryset)
        if obj.owner == self.request.user or self.request.user.has_perm(
                "catalog.delete_product"
        ):
            return obj
        else:
            raise PermissionDenied


class CategoryListView(ListView):
    model = Category
    context_object_name = "categories"


class ProductByCategory(ListView):
    model = Product

    def get_queryset(self):
        print(self.kwargs.get('pk'))
        print(products_by_category(self.kwargs.get('pk')))
        return products_by_category(self.kwargs.get('pk'))

catalog/templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Техника Дома</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">

</head>
<body>
<div class="container">
    <header class="d-flex flex-wrap align-items-center justify-content-center justify-content-md-between py-3 mb-4 border-bottom">
        {% include 'includes/inc_menu2.html' %}
    </header>
</div>

<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">ТехникаДома</h1>
    <p class="lead">Отличный магазин бытовой техники</p>
</div>

<div class="container">
            {% block content %}
            {% endblock %}
            <footer class="pt-4 my-md-5 pt-md-5 border-top">
                <div class="row">
                    <div class="col-12 col-md">
                        Техника Дома
                        <small class="d-block mb-3 text-muted">&copy; 2025</small>
                    </div>
                    <div class="col-6 col-md">
                        <h5>Категории</h5>
                        <ul class="list-unstyled text-small">
                            <li><a class="text-muted" href="#">Рассылки</a></li>
                            <li><a class="text-muted" href="#">Телеграм боты</a></li>
                            <li><a class="text-muted" href="#">Полезные утилиты</a></li>
                            <li><a class="text-muted" href="#">Веб-приложения</a></li>
                            <li><a class="text-muted" href="#">Микросервисы</a></li>
                        </ul>
                    </div>
                    <div class="col-6 col-md">
                        <h5>Дополнительно</h5>
                        <ul class="list-unstyled text-small">
                            <li><a class="text-muted" href="#">Мы пишем</a></li>
                        </ul>
                    </div>
                    <div class="col-6 col-md">
                        <h5>О нас</h5>
                        <ul class="list-unstyled text-small">
                            <li><a class="text-muted" href="{% url 'catalog:contacts_view' %}">Контакты</a></li>
                        </ul>
                    </div>
                </div>
            </footer>
        </div>
    </div>
</div>

<script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
</body>
</html>

catalog/templates/home_view.html
{% extends 'base.html' %}
{% load my_tags %}
{% block content %}
<div class="row">
    {% for product in products %}
    <div class="col-4">
        <div class="card mt-2" style="width: 18rem;">
            <img src="{{ product.photo|media_filter }}" class="card-img-top">
            <div class="card-body">
                <h5 class="card-title">{{ product.name }}</h5>
                <p class="card-text">{{ product.description|truncatechars:100 }}</p>
                <h6>{{product.price}} руб.</h6>
                <p class="card-text"><strong>{{ product.category }}</strong></p>
                <a href="{% url 'catalog:product_detail' product.pk %}" class="btn btn-primary">К товару</a>
            </div>
        </div>
    </div>
    {% endfor %}
</div>
{% endblock %}
Как мне тут применить flex контейнер?

catalog/templates/product_detail.html
{% extends 'base.html' %}
{% load my_tags %}
{% block content %}
<div class="row">
    <div class="col">
        <div class="card mb-3">
            <div class="row g-0">
                <div class="col-md-4">
                    <img src="{{ product.photo|media_filter }}" class="img-fluid rounded-start" alt="...">
                </div>
                <div class="col-md-8">
                    <div class="card-body">
                        <h5 class="card-title mb-4">{{ product.name }}</h5>
                        <p class="card-text">{{ product.description }}</p>
                        <h1><u>{{product.price}} руб.</u></h1>
                        <h5><strong>{{ product.category }}</strong></h5>
                        <a href="{% url 'catalog:home_view' %}" class="btn btn-primary mt-2">Назад</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}