blog/urls.py
from django.urls import path

from blog.apps import BlogConfig
from blog.views import (ArticleCreateView, ArticleDeleteView,
                        ArticleDetailView, ArticleListView, ArticleUpdateView)

app_name = BlogConfig.name


urlpatterns = [
    path("", ArticleListView.as_view(), name="article_list"),
    path("article_detail/<int:pk>", ArticleDetailView.as_view(), name="article_detail"),
    path("create/", ArticleCreateView.as_view(), name="article_create"),
    path("update/<int:pk>", ArticleUpdateView.as_view(), name="article_update"),
    path("delete/<int:pk>", ArticleDeleteView.as_view(), name="article_delete"),
]

catalog/urls.py
from django.urls import path

from catalog.apps import CatalogConfig
from catalog.views import (ContactView, ProductCreateView, ProductDeleteView,
                           ProductDetailView, ProductListView,
                           ProductUpdateView, CategoryListView, ProductByCategory)

app_name = CatalogConfig.name

urlpatterns = [
    path("", ProductListView.as_view(), name="home_view"),
    path("contacts/", ContactView.as_view(), name="contacts_view"),
    path("product_detail/<int:pk>", ProductDetailView.as_view(), name="product_detail"),
    path("product_create/", ProductCreateView.as_view(), name="product_create"),
    path(
        "product_update/<int:pk>/", ProductUpdateView.as_view(), name="product_update"
    ),
    path(
        "product_delete/<int:pk>/", ProductDeleteView.as_view(), name="product_delete"
    ),
    path('categories/', CategoryListView.as_view(), name='category-list'),
    path('product-by-category/<int:pk>/', ProductByCategory.as_view(), name='product-by-category')
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("catalog.urls", namespace="catalog")),
    path("blogs/", include("blog.urls", namespace="blog")),
    path("users/", include("users.urls", namespace="users")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

catalog/models.py
from django.db import models

from users.models import User


class Product(models.Model):
    name = models.CharField(
        max_length=50,
        verbose_name="Название продукта",
        help_text="Введите название продукта",
    )
    description = models.TextField(
        verbose_name="Описание продукта",
        help_text="Введите описание продукта",
        blank=True,
        null=True,
    )
    photo = models.ImageField(upload_to="catalog/photo/", verbose_name="Фотография")
    category = models.ForeignKey(
        "Category", on_delete=models.CASCADE, related_name="products"
    )
    price = models.IntegerField(verbose_name="Цена")
    created_at = models.DateField(auto_now_add=True)
    updated_at = models.DateField(auto_now=True)
    publication_status = models.BooleanField(
        default=False, verbose_name="Флаг для публикации"
    )
    owner = models.ForeignKey(
        to=User,
        on_delete=models.CASCADE,
        verbose_name="Владелец",
        help_text="Укажите владельца",
    )

    class Meta:
        verbose_name = "Продукт"
        verbose_name_plural = "Продукты"
        permissions = [("can_unpublish_product", "Can unpublish product")]

    def __str__(self):
        return self.name


class Category(models.Model):
    name = models.CharField(
        max_length=50,
        verbose_name="Наименование категории",
        help_text="Введите наименование категории",
    )
    description = models.TextField(
        verbose_name="Описание категории",
        help_text="Введите описание категории",
        blank=True,
        null=True,
    )

    class Meta:
        verbose_name = "Категория"
        verbose_name_plural = "Категории"

    def __str__(self):
        return self.name

catalog/forms.py
from django.core.exceptions import ValidationError
from django.forms import BooleanField, ModelForm

from catalog.models import Product

FORBIDDEN_WORDS = [
    "казино",
    "криптовалюта",
    "крипта",
    "биржа",
    "дешево",
    "бесплатно",
    "обман",
    "полиция",
    "радар",
]


class StyleFormMixin:
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for fild in self.fields.values():
            if isinstance(fild, BooleanField):
                fild.widget.attrs.update({"class": "form-check-input"})
            else:
                fild.widget.attrs.update({"class": "form-control"})


class ProductForm(StyleFormMixin, ModelForm):
    class Meta:
        model = Product
        exclude = ("owner",)

    def clean_price(self):
        price = super().clean()["price"]
        if price < 0:
            raise ValidationError("Цена не может быть меньше 0")
        return price

    def clean_description(self):
        description = self.cleaned_data.get("description")
        for word in FORBIDDEN_WORDS:
            if word in description.lower():
                raise ValidationError("Нельзя вводить запрещенные слова")
        return description

    def clean_name(self):
        name = self.cleaned_data.get("name")
        for word in FORBIDDEN_WORDS:
            if word in name.lower():
                raise ValidationError("Нельзя вводить запрещенные слова")
        return name


class ProductFormLimited(ProductForm):
    class Meta:
        model = Product
        exclude = ("publication_status", "owner")

catalog/views.py
from django.contrib.auth.mixins import (LoginRequiredMixin, )
from django.core.exceptions import PermissionDenied
from django.urls import reverse_lazy
from django.views.generic import (CreateView, DeleteView, DetailView, ListView,
                                  TemplateView, UpdateView)
from django.utils.decorators import method_decorator
from django.views.decorators.cache import cache_page
from django.core.cache import cache

from catalog.forms import ProductForm, ProductFormLimited
from catalog.models import Product, Category

from catalog.services import products_by_category


class ContactView(TemplateView):
    template_name = "catalog/contacts.html"


class ProductListView(ListView):
    model = Product

    def get_queryset(self):
        queryset = cache.get('product_list')
        if not queryset:
            queryset = super().get_queryset()
            cache.set('product_list', queryset, 60 * 15)
        return queryset


@method_decorator(cache_page(60 * 15), name='dispatch')
class ProductDetailView(DetailView):
    model = Product


class ProductCreateView(LoginRequiredMixin, CreateView):
    model = Product
    form_class = ProductForm
    success_url = reverse_lazy("catalog:home_view")

    def form_valid(self, form):
        form.instance.owner = self.request.user
        return super().form_valid(form)


class ProductUpdateView(LoginRequiredMixin, UpdateView):
    model = Product
    success_url = reverse_lazy("catalog:home_view")

    def get_form_class(self):
        user = self.request.user
        if user.has_perm("can_unpublish_product"):
            return ProductForm
        else:
            return ProductFormLimited

    def get_object(self, queryset=None):
        obj = super().get_object(queryset=queryset)
        if obj.owner == self.request.user or self.request.user.has_perm(
                "can_unpublish_product"
        ):
            return obj
        else:
            raise PermissionDenied


class ProductDeleteView(LoginRequiredMixin, DeleteView):
    model = Product
    success_url = reverse_lazy("catalog:home_view")

    def get_object(self, queryset=None):
        obj = super().get_object(queryset=queryset)
        if obj.owner == self.request.user or self.request.user.has_perm(
                "catalog.delete_product"
        ):
            return obj
        else:
            raise PermissionDenied


class CategoryListView(ListView):
    model = Category
    context_object_name = "categories"


class ProductByCategory(ListView):
    model = Product

    def get_queryset(self):
        print(self.kwargs.get('pk'))
        print(products_by_category(self.kwargs.get('pk')))
        return products_by_category(self.kwargs.get('pk'))

catalog/templates/catalog/category_list.html
{% extends 'base.html' %}
{% block content %}
<div class="row">
    <div class="col-12">
        <a class="btn btn-primary mb-2" href="{% url 'catalog:home_view' %}">Все товары</a>
    </div>
    {% for category in categories %}
    <div class="col-3">
        <div class="card mb-2" style="width: 15rem; height: 10rem;">
            <div class="card-body">
                <h5 class="card-title">{{ category.name }}</h5>
            </div>
            <div class="card-footer">
                <a href="{% url 'catalog:product-by-category' category.pk %}" class="btn btn-primary">Перейти</a>
            </div>
        </div>
    </div>
    {% endfor %}
</div>
{% endblock %}

catalog/templates/catalog/contacts.html
{% extends 'base.html' %}
{% load my_tags %}
{% block content %}
<div class="row text-start">
        <div class="col-lg-9 col-md-6 col-sm-12">
            <div class="card mb-4 box-shadow">
                <div class="card-body">
                    <table class="table table-striped">
                        <tr>
                            <td class="w-25">Страна</td>
                            <td>Россия</td>
                        </tr>
                        <tr>
                            <td class="w-25">ИНН</td>
                            <td>7700000000</td>
                        </tr>
                        <tr>
                            <td class="w-25">Адрес</td>
                            <td>Россия</td>
                        </tr>
                    </table>
                </div>
            </div>
        </div>
        <div class="col-lg-3 col-md-6 col-sm-12">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">Свяжитесь с нами</h4>
                </div>
                <div class="card-body">
                    <form method="post" action="" class="form-floating">
                        {% csrf_token %}
                        <div class="mb-3">
                            <label for="name">Имя</label>
                            <input type="text" name="name" class="form-control" id="name" placeholder="Ваше имя" required>
                        </div>
                        <div class="mb-3">
                            <label for="phone">Телефон</label>
                            <input type="text" name="phone" class="form-control" id="phone" placeholder="Контактный телефон" required>
                        </div>
                        <div class="mb-3">
                            <label for="message">Сообщение</label>
                            <textarea type="text" name="message" class="form-control" id="message" placeholder="Контактный телефон" required></textarea>
                        </div>
                        <button type="submit" class="btn btn-lg btn-block btn-outline-primary">Отправить</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

catalog/templates/catalog/product_confirm_delete.html
{% extends 'base.html' %}
{% block content %}
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="card mx-auto text-center" style="width: 30rem;">
        <div class="card-body">
            <h5 class="card-title">Вы действительно хотите удалить продукт?</h5>
            <button type="submit" class="btn btn-outline-danger">Удалить</button>
            <a href="{% url 'catalog:home_view' %}" class="btn btn-primary">Отменить</a>
        </div>
    </div>
</form>
{% endblock %}

catalog/templates/catalog/product_detail.html
{% extends 'base.html' %}
{% load my_tags %}
{% block content %}
<div class="row">
    <div class="col">
        <div class="card mb-3">
            <div class="row g-0">
                <div class="col-md-4">
                    <img src="{{ object.photo|media_filter }}" class="img-fluid rounded-start" alt="...">
                </div>
                <div class="col-md-8">
                    <div class="card-body">
                        <h5 class="card-title mb-4">{{ object.name }}</h5>
                        <p class="card-text">{{ object.description }}</p>
                        <h1><u>{{object.price}} руб.</u></h1>
                        <h5><strong>{{ object.category }}</strong></h5>
                        <a href="{% url 'catalog:home_view' %}" class="btn btn-primary mt-2">Назад</a>
                        {% if perms.catalog.delete_product or object.owner == user %}
                        <a href="{% url 'catalog:product_update' object.pk %}" class="btn btn-outline-primary mt-2">Редактировать</a>
                        <a href="{% url 'catalog:product_delete' object.pk %}" class="btn btn-outline-danger mt-2">Удалить</a>
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

catalog/templates/catalog/product_form.html
{% extends 'base.html' %}
{% block content %}
<form method="post" enctype="multipart/form-data">
    <div class="card mx-auto">
        <div class="card-body">
            {% csrf_token %}
            {{ form.as_p }}
        </div>
        <div class="d-grid gap-2 mb-2 mx-2">
            <button class="btn btn-primary" type="submit">Сохранить</button>
            <a href="{% url 'catalog:home_view' %}" class="btn btn-outline-primary">Отменить</a>
        </div>
    </div>
</form>
{% endblock %}

catalog/templates/catalog/product_list.html
{% extends 'base.html' %}
{% load my_tags %}
{% block content %}
<div class="row">
    <div class="col-12">
        <a class="btn btn-primary mb-2" href="{% url 'catalog:category-list' %}">Категории</a>
    </div>
    {% for product in object_list %}
    <div class="col-12 col-sm-6 col-md-4">
        <div class="card mb-2" style="width: 18rem; height: 40rem;">
            <img src="{{ product.photo|media_filter }}" class="card-img-top">
            <div class="card-body">
                <h5 class="card-title">{{ product.name }}</h5>
                <p class="card-text">{{ product.description|truncatechars:100 }}</p>
            </div>
            <div class="card-footer">
                <h6>{{product.price}} руб.</h6>
                <p class="card-text"><strong>{{ product.category }}</strong></p>
                <a href="{% url 'catalog:product_detail' product.pk %}" class="btn btn-primary">К товару</a>
            </div>

        </div>
    </div>
    {% endfor %}
</div>
{% endblock %}